# MetaData
sonar.organization=cesizen3
sonar.projectKey=cesizen3_monorepo

sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

# Language
sonar.language=cs

# Source & Tests
sonar.sources=CESIZen
sonar.tests=CESIZen.Tests

# Coverage (OpenCover or cobertura format)
sonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml

# Exclude folders or files (optional)
sonar.exclusions=**/bin/**,**/obj/**

# Quality Gate
sonar.qualitygate.wait=false
