// <auto-generated />
using System;
using CESIZenModel.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CESIZenModel.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20250510093156_petitc")]
    partial class petitc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CESIZenModel.Entities.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nom_Emotion_Niveau1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom_Emotion_Niveau2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emotions");
                });

            modelBuilder.Entity("CESIZenModel.Entities.RapportEmotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date_Debut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Generation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emotion_Moins_Frequente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emotion_Predominante_Niv1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emotion_Predominante_Niv2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Moyenne_Intensite")
                        .HasColumnType("real");

                    b.Property<int>("Total_Tracker")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RapportEmotions");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("Date_Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("EmotionId")
                        .HasColumnType("int");

                    b.Property<string>("Emotion_Niveau1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emotion_Niveau2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Note_Intensite")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmotionId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Trackers");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Tracker_Rapport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Rapport")
                        .HasColumnType("int");

                    b.Property<int>("RapportId")
                        .HasColumnType("int");

                    b.Property<int>("TrackerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RapportId");

                    b.HasIndex("TrackerId");

                    b.ToTable("Tracker_Rapports");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mdp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Tracker", b =>
                {
                    b.HasOne("CESIZenModel.Entities.Emotion", "Emotion")
                        .WithMany("Trackers")
                        .HasForeignKey("EmotionId");

                    b.HasOne("CESIZenModel.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Trackers")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emotion");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Tracker_Rapport", b =>
                {
                    b.HasOne("CESIZenModel.Entities.RapportEmotion", "Rapport")
                        .WithMany("TrackerRapports")
                        .HasForeignKey("RapportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CESIZenModel.Entities.Tracker", "Tracker")
                        .WithMany("TrackerRapports")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rapport");

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Emotion", b =>
                {
                    b.Navigation("Trackers");
                });

            modelBuilder.Entity("CESIZenModel.Entities.RapportEmotion", b =>
                {
                    b.Navigation("TrackerRapports");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Tracker", b =>
                {
                    b.Navigation("TrackerRapports");
                });

            modelBuilder.Entity("CESIZenModel.Entities.Utilisateur", b =>
                {
                    b.Navigation("Trackers");
                });
#pragma warning restore 612, 618
        }
    }
}
