name: 01-1 - Test Back Front

on:
  workflow_call:

jobs:
  Helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Hello

  Backend:
    needs: [Helloworld]
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: toor
          MARIADB_DATABASE: test
          MARIADB_USER: test
          MARIADB_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      BDD_HOST: 127.0.0.1
      BDD_NAME: test
      BDD_USER: root
      BDD_PASS: toor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore CESIZen.sln

      - name: Build solution
        run: dotnet build CESIZen.sln --no-restore

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run EF Core migrations
        run: dotnet ef database update --project CESIZen --startup-project CESIZen

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Check database connection
        run: mysql --host 127.0.0.1 --port 3306 -u root -ptoor -e "SHOW DATABASES;"

      - name: Populate test DB
        run: mysql --host 127.0.0.1 --port 3306 -u root -ptoor test < CESIZen.Tests/Controllers/insert_test_user.sql

      - name: Run unit tests
        run: dotnet test CESIZen.Tests/CESIZen.Tests.csproj --collect:"XPlat Code Coverage"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-coverage-report
          path: '**/TestResults'
          retention-days: 3
