name: 01 - Integration

on:
    pull_request:
        branches:
            - develop

jobs:
    Test_Back_Front:
        uses: ./.github/workflows/01-1_TestBackFront.yaml

    #Quality_Sonar_Qube:

    #Security_Snyk:

